
INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O n�mero de filhos por casal diminui rapidamente. Para a maioria dos economistas, isso representa um alerta para o futuro.Uma consequ�ncia socioecon�mica para os paises que vivenciam o fen�meno demogr�fico ilustrado � a diminui��o da','OFICIAL','A	oferta de m�o de obra nacional. ','B m�dia de expectativa de vida.','C disponibilidade de servi�os de sa�de. ','D despesa de natureza previdenci�ria.','E imigra��o de trabalhadores qXDOL� FDGRV |A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Em sua formula��o, o spray de pimenta cont�m porcentagens variadas de oleorresina de Capsicum, cujo princ�pio ativo � a capsaicina, e um solvente (um �lcool como etanol ou isopropanol). Em contato com os olhos, pele ou vias respirat�rias, a capsaicina causa um efeito inflemat�rio que gera uma sensa��o de dor e ardor, levando � cegueira tempor�ria. O processo�	desencadeado pela libera��o de neuropept�dios das termina��es nervosas.Quando uma pessoa � atingida com o spray de pimenta nos olhos ou na pele, a lavagem da regi�o atingida com �gua � ineficaz porque a ','OFICIAL','A	rea��o entre etanol e �gua libera calor, intensificando o ardor.','B	solubilidade do princ�pio ativo em �gua � muito baixa, dificultando a sua remo��o.','C	permeabilidade da �gua na pele � muito alta, n�o permitindo a remo��o do princ�pio ativo.','D	solubiliza��o do �leo em �gua causa um maior espalhamento al�m das �reas atingidas.','E	ard�ncia faz evaporar rapidamente a �gua, n�o permitindo que haja contato entre o �leo e o solvente.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A usina de Itaipu � uma das maiores hidrel�tricas do mundo em gera��o de energia. Com 20 unidades geradoras e 14 000 MW de pot�ncia total instalada, apresenta uma queda de 118,4 m e vaz�o nominal de 690	m3/s por unidade geradora. O c�lculo da pot�ncia te�rica leva em conta a altura da massa de �gua represada pela barragem, a gravidade local (10 m/s2) e a densidade da �gua (1 000 kg/m3). A diferen�a entre a pot�ncia te�rica e a instalada � a pot�ncia n�o aproveitada.Qual � a pot�ncia, em MW, n�o aproveitada em cada unidade geradora de Itaipu?','OFICIAL','A	0','B 1,18 ','C 116,96 ','D 816,96 ','E 13 183,04|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A coleta das fezes dos animais dom�sticos em sacolas pl�sticas e o seu descarte em lixeiras convencionais podem criar condi��es de degrada��o que geram produtos prejudiciais ao meio ambiente (Figura 1).   A Figura 2 ilustra o Projeto Park Spark, desenvolvido em Cambridge, MA (EUA), em que as fezes dos animais dom�sticos s�o recolhidas em sacolas biodegrad�veis e jogadas em um biodigestor instalado em parques p�blicos; e os produtos s�o utilizados em equipamentos no pr�prio parque.Uma inova��o desse projeto � possibilitar o(a)','OFICIAL','A	queima de g�s metano.','B	armazenamento de g�s carb�nico. ','C decomposi��o aer�bica das fezes.','D uso mais eficiente de combust�veis f�sseis','E fixa��o de carbono em mol�culas org�nicas. |A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma ambul�ncia A em movimento ret�lineo e uniforme aproxima-se de um observador O, em repouso. A sirene emite um som de frequ�ncia constante fA. O desenho ilustra as frentes de onda do som emitido pela ambul�ncia.2 O observador possui um detector que consegue registrar, no esbo�o de um gr�fico, a frequencia da onda sonoradetectada em fun��o do tempo fO(t), antes e depois da passagem da ambul�ncia por ele.Qual esbolo gr�fico representa a frequ�ncia fO(t) detectada pelo observador?','OFICIAL','A','B','C','D','E|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O benzeno, um importante solvente para a ind�stria qu�mica, � obtido industrialmente pela destila��o do petr�leo. Contudo, tamb�m pode ser sintetizado pela trimeriza��o do acetileno catalisada por ferro met�lico sob altas temperaturas, conforme a equa��o qu�mica:3 C2H2 (g)	C6H6 (l)A energia envolvida nesse processo pode ser calculada indiretamente pela varia��o de entalpia das rea��es de combust�o das subst�ncias participantes, nas mesmas condi��es experimentais:A varia��o de entalpia do processo de trimeriza��o, em kcal, para a forma��o de um mol de benzeno � mais pr�xima de','OFICIAL','A	-1 090.','B -150. ','C -50. ','D +157.','E +470.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Em meados de 2003, mais de 20 pessoas morreram no Brasil ap�s terem ingerido uma suspens�o de sulfato de b�rio utilizada como contraste em exames radiol�gicos. O sulfato de b�rio � um s�lido pouqu�ssimo sol�vel em �gua, que n�o se dissolve mesmo na presen�a de �cidos. As mortes ocorreram porque um laborat�rio farmac�utico forneceu o produto contaminado com carbonato de b�rio, que � sol�vel em meio �cido. Um simples teste para verificar a exist�ncia de �ons b�rio sol�veis poderia ter evitado a trag�dia. Esse teste consiste em tratar a amostra com solu��oaquosa de HCI e, ap�s filtrar paara separar os compostos insol�veis de b�rio, adiciona-se solu��o aquosa de H2SO4 sobre o filtrado e observa-se por 30 min.A presen�a de �ons b�rio sol�veis na amostra � indicada pela','OFICIAL','A	libera��o de calor.','B	altera��o da cor para rosa.','C	precipita��o de um s�lido branco. ','D forma��o de g�s hidrog�nio.','E volatiliza��o de g�s cloro.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os ferom�nios s�o subst�ncias utilizadas na comunica��o entre indiv�duos de uma esp�cie. O primeiro ferom�nio isolado de um inseto foi o bombicol, subst�ncia produzida pela mariposa do bicho-da-seda.O HBombicolO uso de ferom�nios em a��es de controle de insetos-praga est� de acordo com o modelo preconizado para a agricultura do futuro. S�o agentes altamente especificos e seus compostos qu�micos podem ser empregados em determinados cultivos, conforme ilustrado no quadro.Considerando essas estruturas qu�micas, o tipo de estereoisomeria apresentada pelo bombicol � tamb�m apresentada pelo ferom�nio utilizado no controle do inseto','OFICIAL','A	Sitophilus spp. ','B Migdolus fryanus. ','C Anthonomus rubi. ','D Grapholita molesta.','E Scrobipalpuloides absoluta.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O esquema representa, de maneira simplificada, o processo de produ��o de etanol utilizando milho como mat�ria-prima.A etapa de hidr�lise na produ��o de etanol a partir do milho � fundamental para que','OFICIAL','A	a glicose seja convertida em sacarose. ','B as enzimas dessa planta sejam ativadas.','C a macera��o favore�a a solubiliza��o em �gua.','D	o amido seja transformado em substratos utiliz�veis pela levedura.','E	os gr�os com diferentes composi��es qu�micas sejam padronizados.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Durante a primeira fase do projeto de uma usina de gera��o de energia el�trica, os engenheiros da equipe de avalia��o de impactos ambientais procuram saber se esse projeto est� de acordo com as normas ambientais. A nova planta estar� localizada � beira de um rio, cuja temperatura m�dia da �gua � de 25 �C, e usar� a sua �gua somente para refrigera��o. O projeto pretende que a usina opere com 1,0 MW de pot�ncia el�trica e, em raz�o de restri��es t�cnicas, o dobro dessa pot�ncia ser� dissipada por seu sistema de arrefecimento, na forma de calor. Para atender a resolu��o n�mero 430, de 13 de maio de 2011, do Conselho Nacional do Meio Ambiente, com uma ampla margem de seguran�a, os engenheiros determinaram que a �gua s� poder� ser devolvida ao rio com um aumento de temperatura de, no m�ximo, 3 �C em rela��o � temperatura da �gua do rio captada pelo sistema de arrefecimento. Considere o calor especifico da �gua igual a 4 kJ/(kg �C).Para atender essa determina��o, o valor m�nimo do fluxo de �gua, em kg/s, para a refrigera��o da usina deve ser mais pr�ximo de','OFICIAL','A	42. ','B 84. ','C 167. ','D 250. ','E 500.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A figura 1 apresenta o gr�fico da intensidade, em decib�is (dB), da onda sonora emitida por um alto-falante, que est� em repouso, e medida por um microfone em fun��o da frequ�ncia da onda para diferentes dist�ncias: 3 mm, 25 mm, 51 mm e 60 mm. A Figura 2 apresenta um diagrama com a indica��o das diversas faixas do espectro de frequ�ncia sonora para o modelo de alto-falante utilizado neste experimento.Relacionando as informa��es presentes nas figuras 1 e 2, como a intensidade sonora percebida � afetada pelo aumento da dist�ncia do microfone ao alto-falante?','OFICIAL','A	Aumenta na faixa das frequ�ncias m�dias. ','B Diminui na faixa das frequ�ncias agudas. ','C Diminui na faixa das frequ�ncias graves.','D Aumenta na faixa das frequ�ncias m�dias altas. ','E Aumenta na faixa das frequ�ncias m�dias baixas.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','As prote�nas de uma c�lula eucari�tica possuem pept�deos sinais, que s�o sequ�ncias de amino�cidos respons�veis pelo seu endere�amento para as diferentes organelas, de acordo com suas fun��es. Um pesquisador desenvolveu uma nanopart�cula capaz de carregar prote�nas para dentro de tipos celulares espec�ficos. Agora ele quer saber se uma nanopart�cula carregada com uma prote�na bloqueadora do ciclo de Krebs in vitro � capaz de exercer sua atividade em uma c�lula cancerosa, podendo cortar o aporte energ�tico e destruir essas c�lulas.Ao escolher essa prote�na bloqueadora para carregar as nanopart�culas, o pesquisador deve levar em conta um pept�deo sinal de endere�amento para qual organela?','OFICIAL','A	N�cleo.','B	Mitoc�ndria. ','C Peroxissomo.','D Complexo golgiense.','E Ret�culo endoplasm�tico.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O morcego emite pulsos de curta dura��o de ondas ultrass�nicas, os quais voltam na forma de ecos ap�s atingirem objetos no ambiente, trazendo informa��es a respeito das suas dimens�es, suas localiza��es e dos seus poss�veis movimentos. Isso se d� em raz�o da sensibilidade do morcego em detectar o tempo gasto para os ecos voltarem, bem como das pequenas varia��es nas frequ�ncias e nas intensidades dos pulsos ultrass�nicos. Essas caracter�sticas lhe permitem ca�ar pequenas presas mesmo quando est�o em movimento em rela��o a si. Considere uma situa��o unidimensional em que uma mariposa se afasta, em movimento retil�neo e uniforme, de um morcego em repouso.A dist�ncia e velocidade da mariposa, na situa��o descrita, seriam detectadas pelo sistema de um morcego por quais altera��es nas caracter�sticas dos pulsos ultrass�nicos?','OFICIAL','A	Intensidade diminu�da, o tempo de retorno aumentado e a frequ�ncia percebida diminu�da.','B	Intensidade aumentada, o tempo de retorno diminu�do e a frequ�ncia percebida diminu�da.','C	Intensidade diminu�da, o tempo de retorno diminu�do e a frequ�ncia percebida aumentada.','D	Intensidade diminu�da, o tempo de retorno aumentado e a frequ�ncia percebida aumentada.','E	Intensidade aumentada, o tempo de retorno aumentado e a frequ�ncia percebida aumentada.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A minimiza��o do tempo e custo de uma rea��o qu�mica, bem como o aumento na sua taxa de convers�o, caracterizam a efici�ncia de um processi qu�mico. Como consequ�ncia, produtos podem chegar ao consumidor mais baratos. Um dos par�metros que mode a efici�ncia de uma rea��o qu�mica � o seu rendimento molar (R, em %), definida comoR =nproduto / nreagente limitante * 100em que n corresponde ao n�mero de mols. O metanol pode ser obtido pela rea��o entre brometo de metila e hidr�xido de s�dio, conforme a equa��o qu�mica:CH3Br + NaOH ->	CH3OH + NaBrAs massas molares (em g/mol) desses elementos s�o: H = 1; C = 12; O = 16; Na = 23; Br = 80.O rendimento molar da rea��o, em que 32 g de metanol foram obtidos a partir de 142,5 g de brometo de metila e 80 g de hidr�xido de s�dio, � mais pr�ximo de','OFICIAL','A	22%. ','B 40%. ','C 50%. ','D 67%. ','E 75%.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Por apresentar significativa resistividade el�trica, o grafite pode ser utilizado para simular resistores el�tricos em circuitos desenhados no papel, com o uso de l�pis e lapiseiras. Dependendo da espessura e do comprimento das linhas desenhadas, � poss�vel determinar a resist�ncia el�trica de cada tra�ado produzido. No esquema foram utilizados tr�s tipos de l�pis diferentes (2H, HB e 6B) para efetuar tr�s tra�ados distintos.Munido dessas informa��es, um estudante pegou uma folha de papel e fez o desenho de um sorvete de casquinha utilizando-se desses tra�ados. Os valores encontrados nesse experimento, para as resist�ncias el�tricas (R), medidas com o aux�lio de um ohm�metro ligado nas extremidades das resist�ncias, s�o mostrados na figura. Verificou-se que os resistores obedeciam � Lei de Ohm.Na sequ�ncia, conectou o ohm�metro nos terminaisA e B do desenho e, em seguida, conectou-o nos terminaisB e C, anotando as leituras RAB e RBC, respectivamente.Ao estabelecer a raz�oR AB, qual resultado o estudanteobteve?','OFICIAL','A 1','B 4/7','C	10/27','D	4/81','E	4/81|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O carv�o ativado � um material que possui elevado teor de carbono, sendo muito utilizado para a remo��o de compostos org�nicos vol�teis do meio, como o benzeno. Para a remo��o desses compostos, utiliza-se a adsor��o. Esse fen�meno ocorre por meio de intera��es do tipo intermoleculares entre a superf�cie do carv�o (adsorvente) e o benzeno (adsorvato, subst�ncia adsorvida).No caso apresentado, entre o adsorvente e a subst�ncia adsorvida ocorre a forma��o de:','OFICIAL','A	Liga��es dissulfeto. ','B Liga��es covalentes. ','C Liga��es de hidrog�nio.','D Intera��es dipolo induzido - dipolo induzido.','E Intera��es dipolo permanente - dipolo permanente.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Um pesquisador investigou o papel da preda��o por peixes na densidade e tamanho das presas, como poss�vel controle de popula��es de esp�cies ex�ticas em cost�es rochosos. No experimento colocou uma tela sobre uma �rea da comunidade, impedindo o acesso dos peixes ao alimento, e comparou o resultado com uma �rea adjacente na qual os peixes tinham acesso livre. O quadro apresenta os resultados encontrados ap�s 15 dias de experimento.O pesquisador concluiu corretamente que os peixes controlam a densidade dos(as)','OFICIAL','A	algas, estimulando seu crescimento.','B	cracas, predando especialmente animais pequenos. ','C mexilh�es, predando especialmente animais pequenos.','D	quatro esp�cies testadas, predando indiv�duos pequenos.','E	asc�dias, apesar de n�o representarem os menores organismos.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Ao percorrer o trajeto de uma cadeia alimentar, o carbono, elemento essencial e majorit�rio da mat�ria org�nica que comp�e os indiv�duos, ora se encontra em sua forma inorg�nica, ora se encontra em sua forma org�nica. Em uma cadeia alimentar composta por fitopl�ncton, zoopl�ncton, molusco, crust�ceos e peixes ocorre a transi��o desse elemento da forma inorg�nica para a org�nica.Em qual grupo de organismos ocorre essa transi��o?','OFICIAL','A	Fitopl�ncton. ','B Zoopl�ncton. ','C Moluscos.','D Crust�ceos. ','E Peixes.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Dois ve�culos que trafegam com velocidade constante em uma estrada, na mesma dire��o e sentido, devem manter entre si uma dist�ncia m�nima. Isso porque o movimento de um ve�culo, at� que ele pare totalmente, ocorre em duas etapas, a partir do momento em que o motorista detecta um problema que exige uma freada brusca. A primeira etapa � associada�	dist�ncia que o ve�culo percorre entre o intervalo de tempo da detec��o do problema e o acionamento dos freios. J� a segunda se relaciona com a dist�ncia que o autom�vel percorre enquanto os freios agem com desacelera��o constante.Considerando a situa��o descrita, qual esbo�o gr�fico representa a velocidade do autom�vel em rela��o � dist�ncia percorrida at� parar totalmente?','OFICIAL','A','B','C','D','E|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','TEXTO IBioc�lulas combust�veis s�o uma alternativa tecnol�gica para substitui��o das baterias convencionais. Em uma bioc�lula microbiol�gica, bact�rias catalisam rea��es de oxida��o de substratos org�nicos. Liberam el�trons produzidos na respira��o celular para um eletrodo, onde fluem por um circuito externo at� o c�todo do sistema, produzindo corrente el�trica. Uma rea��o t�pica que ocorre em bioc�lulas microbiol�gicas utiliza o acetato como substrato.TEXTO IIEm sistemas bioeletroqu�micos, os potenciais padr�o (E�) apresentam valores caracter�sticos. Para as bioc�lulas de acetato, considere as seguintes semirrea��es de redu��o e seus respectivos potenciais:Nessas condi��es, qual � o n�mero m�nimo de bioc�lulas de acetato, ligadas em s�rie, necess�rias para se obter uma diferen�a de potencial de 4,4 V?','OFICIAL','A	3','B 4 ','C 6 ','D 9','E 15|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A forma��o de co�gulos sangu�neos em veias e art�rias � um dos fatores respons�veis pela ocorr�ncia de doen�as cardiovasculares, como varizes, infarto e acidentes vasculares cerebrais. A preven��o e o tratamento dessas doen�as podem ser feitos com drogas anticoagulantes. A ind�stria farmac�utica estimula a pesquisa de toxinas animais com essa propriedade.Considerando as adapta��es relacionadas aos h�bitos alimentares, os animais adequados ao prop�sito dessas pesquisas s�o os(as)','OFICIAL','A	moluscos fit�fagos ','B moscas sapr�fagas. ','C p�ssaros carn�voros. ','D morcegos frug�voros.','E mosquitos hemat�fagos.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A inven��o e o acoplamento entre engrenagens revolucionaram a ci�ncia na �poca e propiciaram a inven��o de v�rias tecnologias, como os rel�gios. Ao construir um pequeno cron�metro, um relojoeiro usa o sistema de engrenagens mostrado. De acordo com a figura, um motor � ligado ao eixo e movimenta as engrenagens fazendo o ponteiro girar. A frequ�ncia do motor � de 18 RPM, e o n�mero de dentes das engrenagens est� apresentado no quadro.A frequ�ncia de giro do ponteiro, em RPM, �','OFICIAL','A	1. ','B 2. ','C 4.','D 81. ','E 162.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Primeiro, em rela��o �quilo a que chamamos �gua, quando congela, parece-nos estar a olhar para algo que se tornou pedra ou terra, mas quando derrete e se dispersa, esta torna-se bafo e ar; o ar, quando � queimado, torna-se fogo; e, inversamente, o fogo, quando se contrai e se extingue, regressa � forma do ar; o ar, novamente concentrado e contra�do, torna-se nuvem e nevoeiro, mas, a partir destes estados, se for ainda mais comprimido, torna-se �gua corrente, e de �gua torna-se novamente terra e pedras; e deste modo, como nos parece, d�o gera��o uns aos outros de forma c�clica.PLAT�O. Timeu-Cr�tias. Coimbra: CECH, 2011.    Do ponto de vista da ci�ncia moderna, os "quatro elementos" descritos por Plat�o correspondem, na verdade, �s fases s�lida, l�quida, gasosa e plasma da mat�ria. As transi��es entre elas s�o hoje entendidas como consequ�ncias macrosc�picas de transforma��es sofridas pela mat�ria em escala microsc�pica.Excetuando-se a fase de plasma, essas transforma��es sofridas pela mat�ria, em n�vel microsc�pico, est�o associadas a uma','OFICIAL','A	troca de �tomos entre as diferentes mol�culas do material.','B	transmuta��o nuclear dos elementos qu�micos do material.','C	redistribui��o de pr�tons entre os diferentes �tomos do material.','D	mudan�a na estrutura espacial formada pelos diferentes constituintes do material.','E	altera��o nas propor��es dos diferentes is�topos de cada elemento presente no material.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Para cada litro de etanol produzido em uma ind�stria de cana- de-a��car s�o gerados cerca de 18 L de vinha�a que � utilizada na irriga��o das planta��es de cana- de -a��car, j� que cont�m teores m�dios de nutrientes N, P e K iguais a 357 mg/L, 60 mg/L e 2 034 mg/L, respectivamente.SILVA, M. A. S.; GRIEBELER, N. P.; BORGES, L. C. Uso de vinha�a e impactos nas propriedades do solo e len�ol fre�tico. Revista Brasileira de Engenharia Agr�cola e Ambiental, n. 1, 2007 (adaptado).Na produ��o de 27 000 L de etanol, a quantidade total de f�sforo, em kg, dispon�vel na vinha�a ser� mais pr�xima de','OFICIAL','A	1.','B 29. ','C 60. ','D 170. ','E 1 000.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Recentemente um estudo feito em campos de trigo mostrou que n�veis elevados de di�xido de carbono na atmosfera prejudicam a absor��o de nitrato pelas plantas. Consequentemente, a qualidade nutricional desses alimentos pode diminuir � medida que os n�veis de di�xido de carbono na atmosfera atingirem as estimativas para as pr�ximas d�cadas.BLOOM, A. J. et al. Nitrate assimilation is inhibited by elevated CO2 LQ �HOG JURZQ ZKHDW   Nature Climate Change, n. 4, abr. 2014 (adaptado).Nesse contexto, a qualidade nutricional do gr�o de trigo VHUi PRGL�FDGD SULPDULDPHQWH SHOD UHGXomR GH','OFICIAL','A	amido. ','B frutose. ','C lip�deos. ','D celulose. ','E prote�nas.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Pesquisadores recuperaram DNA de ossos de mamute (Mammuthus primigenius) encontrados na Sib�ria, que tiveram sua idade de cerca de 28 mil anos confirmada pela t�cnica do carbono-14    FAPESP. DNA de mamute � revelado. Dispon�vel em: http://agencia.fapesp.br.Acesso em: 13 ago. 2012 (adaptado).A t�cnica de data��o apresentada no texto s� � poss�vel devido �','OFICIAL','A	propor��o conhecida entre carbono-14 e carbono-12 na atmosfera ao longo dos anos.','B	decomposi��o de todo o carbono-12 presente no organismo ap�s a morte.','C fixa��o maior do carbono-14 nos tercidos de organimos ap�s a morte.','D	emiss�o de carbono-12 pelos tecidos de organismos ap�s a morte.','E	transforma��o do carbono-12 em carbono-14 ao longo dos anos.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A vegeta��o apresenta adapta��es ao ambiente, como plantas arb�reas e arbustivas com ra�zes que se expandem horizontalmente, permitindo forte ancoragem no substrato lamacento; ra�zes que se expandem verticalmente, por causa da baixa oxigena��o do substrato; folhas que t�m gl�ndulas para eliminar o excesso de sais; folhas que podem apresentar cut�cula espessa para reduzir a perda de �gua por evapora��o.As caracter�sticas descritas referem-se a plantas adaptadas ao bioma:','OFICIAL','A	Cerrado. ','B Pampas. ','C Pantanal.','D Manguezal.','E Mata de Cocais.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma pessoa � respons�vel pela manuten��o de uma sauna �mida. Todos os dias cumpre o mesmo ritual: colhe folhas de capim-cidreira e algumas folhas de eucalipto. Em seguida, coloca as folhas na sa�da do vapor da sauna, aromatizando-a, conforme representado na figura.Qual processo de separa��o � respons�vel pela aromatiza��o promovida?','OFICIAL','A	Filtra��o simples. ','B Destila��o simples. ','C Extra��o por arraste.','D Sublima��o fracionada. ','E Decanta��o s�lido-l�quido.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os ecossistemas degradados por intensa atividade agr�cola apresentam, geralmente, diminui��o de sua diversidade e perda de sua estabilidade. Nesse contexto, o uso integrado de �rvores aos sistemas agr�colas(sistemas agroflorestais) pode cumpri um papel inovador ao buscar a acelera��o do processo sucessional e, ao mesmo tempo, uma produ��o escalonada e diversificada.Essa � uma estrat�gia de concilia��o entre recupera��o ambiental e produ��o agr�cola, pois','OFICIAL','A	substitui gradativamente as esp�cies cultiv�veis por esp�cies arb�reas.','B	intensifica a fertiliza��o do solo com o uso de t�cnicas apropriadas e biocidas.','C	promove maior diversidade de vida no solo com oaumento da mat�ria org�nica.','D	favorece a dispers�o das sementes cultivadas pela fauna residente nas �reas florestais.','E	cria condi��es para o estabelecimento de esp�cies pioneiras com a diminui��o da insola��o sobre o solo.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Tr�s l�mpadas id�nticas foram ligadas no circuito esquematizado. A bateria apresenta resist�ncia interna desprez�vel, e os fios possuem resist�ncia nula. Um t�cnico fez uma an�lise do circuito para prever a corrente el�trica nos pontos:  , B, C, D e E; e rotulou essas correntes de IA, IB, IC, ID e IE, respectivamente.O t�cnico concluiu que as correntes que apresentam o mesmo valor s�o','OFICIAL','A	IA = IE e IC = ID.','B IA = IB = IE e IC = ID. ','C IA = IB, apenas.','D IA = IB = IE, apenas. ','E IC = IB, apenas.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A figura ilustra o movimento da seiva xil�mica em uma plantaMesmo que essa planta viesse a sofrer a��o cont�nua do vento e sua copa crescesse voltada para baixo, essa seiva continuaria naturalmente seu percurso.O que garante o transporte dessa seiva � a','OFICIAL','A	guta��o.','B gravidade. ','C respira��o. ','D fotoss�ntese. ','E transpira��o.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Nucle�filos(Nu) s�o bases de Lewis que reagem com haletos de alquila, por meio de uma rea��o chamada substitui��o nucleof�lica (SN), como mostrado no esquema:R-X + Nu 	R-Nu + X 	(R = grupo alquila e X = halog�nio)A rea��o de SN entre met�xido de s�dio (Nu  = CH3O ) e brometo de metila fornece um composto org�nico pertencente � fun��o','OFICIAL','A	�ter. ','B �ster. ','C �lcool. ','D haleto.','E hidrocarboneto.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O trilho de ar � um dispositivo utilizado em laborat�rios de f�sica para analisar movimentos em que corpos de prova (carrinhos) podem se mover com atrito desprez�vel. A figura ilustra um trilho horizontal com dois carrinhos (1 e 2) em que se realiza um experimento para obter a massa do carrinho 2. No instante em que o carrinho 1, de massa 150,0 g, passa a se mover com velocidade escalar constante, o carrinho 2 est� em repouso. No momento em que o carrinho 1 se choca com o carrinho 2, ambos passam a se movimentar juntos com velocidade escalar constante. Os sensores eletr�nicos distribu�dos ao longo do trilho determinam as posi��es e registram os instantes associados � passagem de cada carrinho, gerando os dados do quadro.Com base nos dados experimentais, o valor da massa do carrinho 2 � igual a','OFICIAL','A	50,0 g. ','B 250,0 g. ','C 300,0 g. ','D 450,0 g. ','E 600,0 g.|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Ap�s seu desgaste completo, os pneus podem ser queimados para a gera��o de energia. Dentre os gases gerados na combust�o completa da borracha vulcanizada, alguns s�o poluentes e provocam a chuva �cida. Para evitar que escapem para a atmosfera, esses gases podem ser borbulhados em uma solu��o aquosa contendo uma subst�ncia adequada. Considere as informa��es das subst�ncias listadas no quadro.Subst�nciaEquil�brio em solu��o aquosaValor da constante de equil�brioDentre as subst�ncias listadas no quadro, aquela capaz de remover com maior efici�ncia os gases poluentes � o(a)','OFICIAL','A	fenol.','B piridina.','C metilamina.','D hidrogenofosfato de pot�ssio. ','E hidrogenosulfato de pot�ssio.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','V�rios m�todos s�o empregados para preven��o de infec��es por microrganismos. Dois desses m�todos utilizam microrganismos vivos e s�o eles: as vacinas atenuadas, constitu�das por pat�genos avirulentos, e os probi�ticos que cont�m bact�rias ben�ficas. Na figura s�o apresentados cinco diferentes mecanismos de exclus�o de pat�genos pela a��o dos probi�ticos no intestino de um animal.Qual mecanismo de a��o desses probi�ticos promove um efeito similar ao da vacina?','OFICIAL','A	5','B 4 ','C 3 ','D 2 ','E 1|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O Painel Intergovernamental de Mudan�as Clim�ticas (na sigla em ingl�s, IPCC) prev� que nas pr�ximas d�cadas o planeta passar� por mudan�as clim�ticas e prop�e estrat�gias de mitiga��o e adapta��o a elas. As estrat�gias de mitiga��o s�o direcionadas � causa dessas mudan�as, procurando reduzir a concentra��o de gases de efeito estufa na atmosfera. As estrat�gias de adapta��o, por sua vez, s�o direcionadas aos efeitos dessas mudan�as, procurando preparar os sistemas humanos �s mudan�as clim�ticas j� em andamento, de modo a reduzir seus efeitos negativos.IPCC, 2014. Climate Change 2014: synthesis report. Dispon�vel em: http://ar5-syr.ipcc.ch. Acesso em: 22 out. 2015 (adaptado).Considerando as informa��es do texto, qual a��o representa uma estrat�gia de adapta��o?','OFICIAL','A	Constru��o de usinas e�licas. ','B Tratamento de res�duos s�lidos.','C Aumento da efici�ncia dos ve�culos. ','D Ado��o de agricultura sustent�vel de baixo carbono. ','E Cria��o de diques de conten��o em regi�es costeiras.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','A lipofilia � um dos fatores fundamentais para o planejamento de um f�rmaco. Ela mede o grau de afinidade que a subst�ncia tem com ambientes apolares, podendo ser avaliada por seu coeficiente de parti��o.Em rela��o ao coeficiente de parti��o da testosterona, as lipofilias dos compostos 1 e 2 s�o, respectivamente,','OFICIAL','A	menor e menor que a lipofilia da testosterona  ','B menor e maior que a lipofilia da testosterona ','C maior e menor que a lipofilia da testosterona.  ','D maior e maior que a lipofilia da testosterona. ','E menor e igual � lipofilia da testosterona.|D','|D');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Uma inven��o que significou um grande avan�o  tecnol�gico na Antiguidade, a polia composta ou a associa��o de polias, � atribu�da a Arquimedes (287 a.C. a 212 a.C.). O aparato consiste em associar uma s�rie de poliasm�veis a uma polia fixa. A figura exemplifica um arranjo poss�vel para esse aparato. � relatado que Arquimedes teria demonstrado para o rei Hier�o um outro arranjo desse aparato, movendo sozinho, sobre a areia da praia, um navio repleto de passageiros e cargas, algo que seria imposs�vel sem a participa��o de muitos homens. Suponha que a massa do navio era de 3 000 kg, que o coeficiente de atrito est�tico entre o navio e a areia era de 0,8 e que Arquimedes tenha puxado o navio com umafor�a F , paralela � dire��o do movimento e de m�dulo igual a 400 N. Considere os fios e as polias ideias, a acelera��o da gravidade igual a 10 m/s2 e que a superf�cie da praia � perfeitamente horizontal.O n�mero m�nimo de polias m�veis usadas, nessa situa��o, por Arquimedes foi','OFICIAL','A	3. ','B 6. ','C 7. ','D 8.','E 10.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O Brasil possui um grande n�mero de esp�cies distintas entre animais, vegetais e microrganismos envoltos em uma imensa complexidade e distribu�das em uma grande variedade de ecossistemas.O incremento da variabilidade ocorre em raz�o da permuta gen�tica, a qual propicia a troca de segmentos entre crom�tides n�o irm�s na meiose.Essa troca de segmentos � determinante na','OFICIAL','A	produ��o de indiv�duos mais f�rteis.','B	transmiss�o de novas caracter�sticas adquiridas. ','C recombina��o gen�tica na forma��o dos gametas. D ocorr�ncia de muta��es som�ticas nos descendentes.','E	varia��o do n�mero de cromossomos caracter�stico da esp�cie.|C','','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Num experimento, um professor deixa duas bandejas de mesma massa, uma de pl�stico e outra de alum�nio, sobre a mesa do laborat�rio. Ap�s algumas horas, ele pede aos alunos que avaliem a temperatura das duasbandejas, usando para isso o tato. Seus alunos afirmam, categoricamente, que a bandeja de alum�nio encontra-se numa temperatura mais baixa. Intrigado, ele prop�e uma segunda atividade, em que coloca um cubo de gelo sobre cada uma das bandejas, que est�o em equil�brio t�rmico com o ambiente, e os questiona em qual delas a taxa de derretimento do gelo ser� maior.O aluno que responder corretamente ao questionamento do professor dir� que o derretimento ocorrer�','OFICIAL','A	mais rapidamente na bandeja de alum�nio, pois ela tem uma maior condutividade t�rmica que a de pl�stico.','B	mais rapidamente na bandeja de pl�stico, pois ela tem inicialmente uma temperatura mais alta que a de alum�nio.','C	mais rapidamente na bandeja de pl�stico, pois ela tem uma maior capacidade t�rmica que a de alum�nio.','D	mais rapidamente na bandeja de alum�nio, pois ela tem um calor espec�fico menor que a de pl�stico.','E	com a mesma rapidez nas duas bandejas, pois apresentar�o a mesma varia��o de temperatura.|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Os tensoativos s�o compostos capazes de interagir com subst�ncias polares e apolares. A parte i�nica dos tensoativos interage com subst�ncias polares, e a parte lipof�lica interage com as apolares. A estrutura org�nica de um tensoativo pode ser representada por:Ao adicionar um tensoativo sobre a �gua, suas mol�culas formam um arranjo ordenado.Esse arranjo � representado esquematicamente por:','OFICIAL','A','B','C','D','E|C','|C');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Um experimento para comprovar a natureza ondulat�ria da radia��o de micro-ondas foi realizado da seguinte forma: anotou-se a frequ�ncia de opera��o de um forno de micro-ondas e, em seguida, retirou-se sua plataforma girat�ria. No seu lugar, colocou-se uma travessa refrat�ria com uma camada grossa de manteiga. Depois disso, o forno foi ligado por alguns segundos. Ao se retirar a travessa refrat�ria do forno, observou-se que havia tr�s pontos de manteiga derretida alinhados sobre toda a travessa. Parte da onda estacion�ria gerada no interior do forno � ilustrada na figura.De acordo com a figura, que posi��es correspondem a dois pontos consecutivos da manteiga derretida?','OFICIAL','A	I e III ','B I e V ','C II e III','D II e IV ','E II e V|A','|A');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Portadores	de	diabetes	insipidus	reclamam	daconfus�o feita pelos profissionais da sa�de quanto aos dois tipos de diabetes: mellitus e insipidus. Enquanto o primeiro tipo est� associado aos n�veis ou � a��o da insulina, o segundo n�o est� ligado � defici�ncia dessehorm�nio. O diabetes insipidus � caracterizado por um dist�rbio na produ��o ou no funcionamento do horm�nio antidiur�tico (na sigla em ingl�s, ADH), secretado pela neuro-hip�fise para controlar a reabsor��o de �gua pelos t�bulos renais.Tendo em vista o papel funcional do ADH, qual � um sintoma cl�ssico de um paciente acometido por diabetes insipidus?','OFICIAL','A	Alta taxa de glicose no sangue. ','B Aumento da press�o arterial. ','C Ganho de massa corporal.','D Anemia cr�nica. ','E Desidrata��o.|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','','OFICIAL','A	o campo magn�tico gerado pela oscila��o das nanopart�culas � absorvido pelo tumor.','B	o campo magn�tico alternado faz as nanopart�culas girarem, transferindo calor por atrito.','C	as nanopart�culas interagem magneticamente com as c�lulas do corpo, transferindo calor.','D	o campo magn�tico alternado fornece calor para as nanopart�culas que o transfere �s c�lulas do corpo.','E	as nanopart�culas s�o aceleradas em um �nico sentido em raz�o da intera��o com o campo magn�tico, fazendo-as colidir com as c�lulas e transferir calor.|B','|B');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','O aquecimento de um material por irradia��o com micro-ondas ocorre por causa da intera��o da onda eletromagn�tica com o dipolo el�trico da mol�cula. Um importante atributo do aquecimento por micro-ondas�	a absor��o direta da energia pelo material a ser aquecido. Assim, esse aquecimento � seletivo e depender�, principalmente, da constante diel�trica e da frequ�ncia de relaxa��o do material. O gr�fico mostra a taxa de aquecimento de cinco solventes sob irradia��o de micro-ondas.No gr�fico, qual solvente apresenta taxa m�dia de aquecimento mais pr�xima de zero, no intervalo de0 s a 40 s?','OFICIAL','A	H2O ','B CH3OH','C CH3CH2OH ','D CH3CH2CH2OH','E CH3CH2CH2CH2CH2CH3|E','|E');



INSERT INTO questao (idusuario,idprova,idareaconhecimento,enunciado,questaooficial,respostaa,respostab,respostac,respostad,respostae,respostacorreta) VALUES('0','0','0','Apesar da grande diversidade biol�gica, a hip�tese de que a vida na Terra tenha tido uma �nica origem comum � aceita pela comunidade cientifica.Uma evid�ncia que apoia essa hip�tese � a observa��o de processos biol�gicos comuns a todos os seres vivos atualmente existentes.Um exemplo de tal processo � o(a)','OFICIAL','A	desenvolvimento embrion�rio. ','B reprodu��o sexuada.','C respira��o aer�bica. ','D excre��o urin�ria. ','E s�ntese proteica.|E','|E');


